server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://rm-bp15v1ahz3q8eb389xo.mysql.rds.aliyuncs.com:3306/lecture_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: lecture_root
    password: Lecture123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: r-bp1velmtv10jqnmyr6pd.redis.rds.aliyuncs.com
    port: 6379
    password: Lecture123
    # 数据库
    database: 0
    # 连接超时
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 8
        # 最小空闲连接，默认0
        min-idle: 5

dubbo:
  application:
    name: lecture-provider
  registry:
    address: zookeeper://119.3.15.104:2181
    timeout: 6000
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: com.study.lecture.lecture.service.impl

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true