server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://rm-bp15v1ahz3q8eb389xo.mysql.rds.aliyuncs.com:3306/lecture_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: lecture_root
    password: Lecture123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.150.101
    port: 6379
    # 数据库
    database: 0
    # 连接超时
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 8
        # 最小空闲连接，默认0
        min-idle: 5