server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://rm-bp15v1ahz3q8eb389xo.mysql.rds.aliyuncs.com:3306/lecture_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: lecture_root
    password: Lecture123
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: lecture-publish
  registry:
    address: zookeeper://192.168.150.101:2181

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml