server:
  port: 8003

dubbo:
  application:
    name: oss-provider
  registry:
    address: zookeeper://119.3.15.104:2181
    timeout: 6000
  protocol:
    name: dubbo
    port: 20883
  scan:
    base-packages: com.study.lecture.oss.service.impl
